### ISSUE TITLE
Adding this addon to a react library results in a hooks error in a consuming react app

### ISSUE THREAD

**Issue by hergaiety** [aholachek/storybook-mobile#25]
## Problem:
Creating a react component library where components that use react hooks that have storybook and storybook-mobile throw a hooks error in a consuming react app that uses said library.

The issue is _very_ likely caused by [this project's package.json's devDependencies](https://github.com/aholachek/storybook-mobile/blob/master/package.json#L49) including `react` and `react-dom` when they should be only `peerDependencies`.

## Proposed solution:

I'm unsure of exactly what the cleanest way to solve this is, but I believe it's moving `react-dom` to `peerDependencies` and ensuring that both `react` and `react-dom` are not in `dependencies` or `devDependencies`. You'll also likely want to update the steps for working on this addon locally to mention that those will need to be fetched manually to dev this addon, I suggest `npm i --no-save react react-dom`.

I'd be happy to PR this if it sounds good to the main contributor(s).

### Isolated repo with reproduction
https://gitlab.com/gaiety/react-peer-dependencies-storybook-mobile-repro (should just be able to `yarn` in both, `yarn start` in the app)

### or repeat the manual steps I took...
1. `npx create-react-library library` using all default options
2. `npx create-react-app app`
3. Modify `./library/src/index.js` to use a React hook, such as:
```js
import React, { useState } from 'react'

export const ExampleComponent = () => {
  const [foo] = useState('example')
  return <div>Example Component: {foo}</div>
}
```
4. Modify `./library/package.json` to remove `react` and `react-dom` from the `devDependencies`, and add `react-dom` to the `peerDependencies`
5. From `./library` install storybook with `npx sb init`
6. Modify `./app/package.json` to consume the library adding `"library": "link:../library",` to its dependencies
7. Modify `./app/src/App.js` to use this component like so:
```jsx
import { ExampleComponent } from 'library';
//... then somewhere in the returned JSX
<ExampleComponent />
```
8. From `./library` run `yarn` and then `yarn build`
9. From './app' run `yarn` and then `yarn start`
> Observe at this point that the app works, showing the component that uses hooks flawlessly in the browser
> Also observe that there is no `react` or `react-dom` in the library's `node_modules` directory
10. Install `storybook-mobile` into the library following [this project's getting started steps](https://github.com/aholachek/storybook-mobile#quick-start) then `yarn start` the **app** again
> Observe the classic and cryptic `Error: Invalid hook call.` appears, signifying in this case multiple copies of react exist.
> Also observe that there is now a `react` and `react-dom` in the library's `node_modules` directory

**Comment by aholachek** [comment]
Hi, thank you for this detailed report and sorry for the delay in response. I'm a little hazy on the best practices-- I always assumed that putting React in both `peerDependencies` and `devDependencies` was "the right way" to go about things. But, if it's causing problems I'm definitely happy to test and merge your proposed solution .

**Comment by hergaiety** [comment]
@aholachek thanks for being willing to test and merge! And, if anything, you've had a prompt response haha. This isn't exactly the most fun bug to wake up too or the easiest to follow. So, I appreciate your time.

**Comment by hergaiety** [comment]
@aholachek just wanted to circle back and say that I've been able to successfully add this library into my project once again with the latest release. Thanks again for your effort testing and pushing up a new release! Excited to be using this tool again.
