### ISSUE TITLE
More issues shown next to tab than there actually are

### ISSUE THREAD

**Issue by CodeByAlex** [aholachek/storybook-mobile#3]
As you can see here, the tab says there are 2 warnings/hints but only one appears. Either the panel is missing a hint or the number of issues is incorrect.
![image](https://user-images.githubusercontent.com/29763590/81682790-2690a000-9423-11ea-8c53-404e8c16eab3.png)

Great addon btw! Thanks for your contribution 👍

**Comment by CodeByAlex** [comment]
Does this mean that there are 2 of the same issue? If so, is there a way to make that more obvious to the user?

**Comment by aholachek** [comment]
I just released v0.1.20 which handles the warning count in the tab a little more cleanly, which will hopefully prevent the problem you saw from happening.
