### ISSUE TITLE
-webkit-overflow-scrolling:touch rule applied when overflow is in a state other than auto or scroll

### ISSUE THREAD

**Issue by CodeByAlex** [aholachek/storybook-mobile#4]
To ensure your users benefit from momentum scrolling, add this line of CSS: -webkit-overflow-scrolling:touch; to any container with a style of overflow: auto or overflow: scroll.

The above rule is applied when overflow is in a state other than auto or scroll. If this is expected behavior, it should add etc. to the language or list out the possibilities. If not, the check should look for auto or scroll.

**Comment by aholachek** [comment]
You're right that [the code checks for `overflow-x` and `overflow-y` in addition to just `overflow`.](https://github.com/aholachek/storybook-mobile/blob/master/src/utils.js#L160) 

Is that what you mean-- that ideally you'd want to see those attributes listed as well? Or maybe I'm misunderstanding, and there is a bug and the rule is applying to containers it shouldn't be?

**Comment by CodeByAlex** [comment]
I guess I’m just wondering if it applies that rule if it recognizes overflow it’s any value. Write now I have overflow: hidden in my code and it’s still suggesting that I use touch. Is that correct?

**Comment by aholachek** [comment]
Nope, that is definitely a bug, I will try to reproduce and fix. Thanks for flagging.

**Comment by CodeByAlex** [comment]
Hey @aholachek - is there any update on a fix for this bug? I’d love to get this integrated into our orgs repos but I don’t want to do so until the false positives defined in this PR are fixed.

**Comment by aholachek** [comment]
Hi @CodeByAlex, after some back and forth with having trouble reproducing this, I decided to remove the rule since it only affects iOS 12 and below (which is something like <2-3% of mobile users at the moment according to "netmarketshare.com", not sure how reliable that is).

**Comment by aholachek** [comment]
The most recent release is the one that removed the rule: https://github.com/aholachek/storybook-mobile/releases/tag/v0.1.22
